language: php

sudo: false

services:
  - mysql

matrix:
  fast_finish: true
  include:
    # SQLite
    - php: 7.0
      env: CI_DB_DRIVER="sqlite" CI_DB_DATABASE=":memory:"
    - php: 7.1
      env: CI_DB_DRIVER="sqlite" CI_DB_DATABASE=":memory:"
    # MySQL 5.7
    - php: 7.0
      env: CI_DB_DRIVER="mysql" CI_DB_HOST="127.0.0.1" CI_DB_DATABASE="travis" CI_DB_USERNAME="root"
    - php: 7.1
      env: CI_DB_DRIVER="mysql" CI_DB_HOST="127.0.0.1" CI_DB_DATABASE="travis" CI_DB_USERNAME="root"
    # MariaDB
    - php: 7.0
      env: CI_DB_DRIVER="mysql" CI_DB_HOST="127.0.0.1" CI_DB_DATABASE="travis" CI_DB_USERNAME="root"
      addons:
        mariadb: 10.0
    - php: 7.1
      env: CI_DB_DRIVER="mysql" CI_DB_HOST="127.0.0.1" CI_DB_DATABASE="travis" CI_DB_USERNAME="root"
      addons:
        mariadb: 10.0

install: travis_retry composer install --no-interaction --prefer-source

script:
  - mysql --version
  - vendor/bin/phpunit --verbose
